FROM node:24

ARG ADMIN_CHAT_ID_ARG
ARG CHANNEL_ID_ARG
ARG GROUP_CHAT_ID_ARG
ARG MODERATOR_CHAT_ID_ARG
ARG TELEGRAM_BOT_TOKEN_ARG

ENV ADMIN_CHAT_ID=$ADMIN_CHAT_ID_ARG
ENV CHANNEL_ID=$CHANNEL_ID_ARG
ENV GROUP_CHAT_ID=$GROUP_CHAT_ID_ARG
ENV MODERATOR_CHAT_ID=$MODERATOR_CHAT_ID_ARG
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN_ARG

ENV NODE_ENV=PRODUCTION

WORKDIR /app

COPY ./backend/ ./

RUN npm ci
RUN npm i -g @nestjs/cli
RUN npm run build

CMD ["npm", "run", "start:prod"]