env:
  DOCKER_IMAGE_NAME: "beny-bot-image"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        run: |
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker build . --tag ${{ env.DOCKER_IMAGE_NAME }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}